- name: install pack 
  package:
    name: "{{ package_name }}"
    state: "{{ package_state }}"

- name: Copy files 
  copy:
    src: "{{ item }}"
    dest: /home/myhost/
  with_fileglob:
    - roles/web/files/*
  notify: my_handler

  
- name: template_task
  template:
    src: index.html.j2
    dest: /var/www/html/index.html


